"""initial migration

Revision ID: eaf5c45ffaa
Revises: None
Create Date: 2014-12-26 15:04:39.973134

"""

# revision identifiers, used by Alembic.
revision = 'eaf5c45ffaa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
